name: d_m
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1   # Firebase Authentication
  google_sign_in: ^6.2.1   # Google Sign-In SDK
  cloud_firestore: ^5.6.5 # Firestore (if you're storing user details)
  firebase_analytics: ^11.4.4 # Google Analytics for Firebase
  get: ^4.7.2
  provider: ^6.1.2
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2
  mobile_scanner: ^6.0.7
  share_plus: ^10.1.4
  multi_select_flutter: ^4.1.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.1.12

  google_maps_flutter: ^2.11.0

  geolocator: ^13.0.3
  flutter_polyline_points: ^2.1.0
  permission_handler: ^11.4.0
  http: ^1.3.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  flutter_bloc: ^9.1.0
  intl: ^0.19.0
  flutter_background_service: ^5.1.0

  geocoding: ^3.0.0

  location: ^8.0.0
  dio: ^5.8.0+1
  google_maps_flutter: ^2.11.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chatbot.png
    - assets/images/logo.png
    - assets/images/default_user.png

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true
  fullscreen: true
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#000000"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#000000"
    branding: assets/images/logo.png
    branding_dark: assets/images/logo.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # Path to your 400x400 icon
  adaptive_icon_background: "#000000" # Background color for adaptive icons (Android)
  adaptive_icon_foreground: "assets/images/logo.png" # Foreground for adaptive icons